import { expect, test, type Page } from '@playwright/test';

/**
 * The public site: the pages a search engine and a first-time visitor see.
 *
 * These run without a signed-in user on purpose. Everything asserted here is
 * either a launch-blocking SEO artefact (robots, sitemap, canonical, social
 * card) or a promise the marketing copy makes that has to be kept — and none of
 * it needs a database, so it runs on every commit rather than only when the
 * full stack is up.
 */

const PUBLIC_PAGES = ['/', '/pricing', '/docs', '/security', '/privacy', '/terms'] as const;

/** Routes that must never be reachable, or indexable, without a session. */
const PRIVATE_PAGES = [
  '/graphs',
  '/connections',
  '/runs',
  '/usage',
  '/settings',
  '/settings/security',
  '/settings/data',
  '/settings/workspaces',
  '/settings/billing',
  '/billing',
] as const;

async function horizontalOverflow(page: Page): Promise<number> {
  return page.evaluate(
    () => document.documentElement.scrollWidth - document.documentElement.clientWidth,
  );
}

test.describe('crawler artefacts', () => {
  test('serves a robots.txt that points at the sitemap and hides private routes', async ({
    request,
  }) => {
    const response = await request.get('/robots.txt');
    expect(response.status()).toBe(200);

    const body = await response.text();
    expect(body).toContain('Sitemap:');
    expect(body).toContain('sitemap.xml');

    // Every authenticated section. `noindex` on the pages themselves is the
    // control that actually matters, but a crawler that never fetches them
    // cannot leak one through a referrer either.
    for (const section of ['/graphs', '/connections', '/runs', '/usage', '/settings', '/billing']) {
      expect(body, `robots.txt does not disallow ${section}`).toContain(`Disallow: ${section}`);
    }
    expect(body).toContain('Disallow: /api/');
  });

  test('serves a sitemap listing the public pages and nothing private', async ({ request }) => {
    const response = await request.get('/sitemap.xml');
    expect(response.status()).toBe(200);

    const body = await response.text();
    for (const path of PUBLIC_PAGES) {
      const suffix = path === '/' ? '/' : path;
      expect(body, `sitemap is missing ${path}`).toContain(`${suffix}</loc>`);
    }

    // The failure this guards: a sitemap generated by walking the route tree
    // would eventually hand a crawler the URL of somebody's settings page.
    for (const path of PRIVATE_PAGES) {
      expect(body, `sitemap leaks ${path}`).not.toContain(`${path}</loc>`);
    }
  });

  test('renders a social card image', async ({ request }) => {
    const response = await request.get('/opengraph-image');
    expect(response.status()).toBe(200);
    expect(response.headers()['content-type']).toContain('image/png');

    // A card that is a few hundred bytes is a card that failed to draw.
    const body = await response.body();
    expect(body.byteLength).toBeGreaterThan(5_000);
  });
});

test.describe('the homepage', () => {
  test('has exactly the wordmark as its title, with no tagline appended', async ({ page }) => {
    await page.goto('/');
    // Deliberately an equality assertion. A `template` in the root metadata, or
    // a per-route title, would turn this into "Toolgraph — something" and that
    // is specifically not wanted.
    await expect(page).toHaveTitle('Toolgraph');
  });

  test('declares a canonical url and a large social card', async ({ page }) => {
    await page.goto('/');

    const canonical = page.locator('link[rel="canonical"]');
    await expect(canonical).toHaveCount(1);
    expect(await canonical.getAttribute('href')).toBeTruthy();

    // Both hostnames serve the same pages (the apex redirects to www), so
    // without a canonical a crawler has two URLs for every one page.
    await expect(page.locator('meta[name="twitter:card"]')).toHaveAttribute(
      'content',
      'summary_large_image',
    );
    await expect(page.locator('meta[property="og:image"]')).toHaveCount(1);
  });

  test('carries structured data that parses and matches the visible FAQ', async ({ page }) => {
    await page.goto('/');

    const raw = await page.locator('script[type="application/ld+json"]').first().textContent();
    expect(raw).toBeTruthy();

    const parsed = JSON.parse(raw as string) as { '@graph': { '@type': string }[] };
    const types = parsed['@graph'].map((node) => node['@type']);
    expect(types).toContain('SoftwareApplication');
    expect(types).toContain('FAQPage');

    // Markup that does not match the rendered page is what search engines treat
    // as spam. The questions must actually be on the page.
    const faq = parsed['@graph'].find((node) => node['@type'] === 'FAQPage') as {
      mainEntity: { name: string }[];
    };
    for (const question of faq.mainEntity) {
      await expect(
        page.getByRole('heading', { name: question.name, exact: true }),
        `"${question.name}" is in the structured data but not on the page`,
      ).toBeVisible();
    }
  });

  test('has one h1 and a sensible heading order', async ({ page }) => {
    await page.goto('/');
    await expect(page.locator('h1')).toHaveCount(1);
    // At least one section heading below it, so the page is not a wall.
    expect(await page.locator('h2').count()).toBeGreaterThan(0);
  });
});

test.describe('every public page', () => {
  for (const path of PUBLIC_PAGES) {
    test(`${path} renders, is indexable, and links onward`, async ({ page }) => {
      const response = await page.goto(path);
      expect(response?.status()).toBe(200);

      await expect(page.locator('h1')).toHaveCount(1);

      // No accidental noindex on a page meant to be found.
      const robots = page.locator('meta[name="robots"]');
      if ((await robots.count()) > 0) {
        expect(await robots.first().getAttribute('content')).not.toContain('noindex');
      }

      // The footer is how a crawler reaches /security, /privacy and /terms at
      // all — nothing else on the site points at them.
      await expect(
        page.getByRole('contentinfo').getByRole('link', { name: 'Privacy' }),
      ).toBeVisible();
    });

    test(`${path} does not scroll sideways on a phone`, async ({ page }) => {
      await page.setViewportSize({ width: 320, height: 568 });
      await page.goto(path);
      expect(await horizontalOverflow(page)).toBeLessThanOrEqual(0);
    });
  }
});

test.describe('pricing', () => {
  test('offers a real monthly/annual toggle that changes the price', async ({ page }) => {
    await page.goto('/pricing?interval=monthly');
    await expect(page.getByText('$15', { exact: true }).first()).toBeVisible();

    await page.getByRole('link', { name: 'Annual', exact: false }).click();
    await page.waitForURL(/interval=annual/);

    // The annual figure is its own number in the price table, not the monthly
    // one multiplied at render time — so this is a different value, not a
    // relabelled one.
    await expect(page.getByText('$150', { exact: true }).first()).toBeVisible();
  });

  test('shows all three plans, including Team', async ({ page }) => {
    await page.goto('/pricing');
    for (const plan of ['Free', 'Pro', 'Team']) {
      await expect(page.getByRole('heading', { name: plan, exact: true })).toBeVisible();
    }
  });

  test('does not claim a certification it does not have', async ({ page }) => {
    // A guard against somebody adding a trust badge later. Toolgraph has no
    // SOC 2 and no ISO 27001, and the security page says so explicitly.
    await page.goto('/pricing');
    const body = (await page.textContent('body')) ?? '';
    expect(body).not.toMatch(/SOC ?2 (certified|compliant)/i);
    expect(body).not.toMatch(/ISO ?27001 (certified|compliant)/i);
  });
});

test.describe('private routes', () => {
  for (const path of PRIVATE_PAGES) {
    test(`${path} sends a signed-out visitor to sign in`, async ({ page }) => {
      await page.goto(path);
      // The middleware issues a real 307 before any page code runs, so the
      // browser lands on /login rather than on a shell that then redirects.
      await expect(page).toHaveURL(/\/login/);
    });
  }
});
