/**
 * The TypeScript export.
 *
 * The bundle this produces must keep working after toolgraph is deleted from
 * the user's machine, so the only imports it may emit are `zod` and the
 * official MCP SDK. Nothing here writes an import that points back at this
 * repository, and `typescript.test.ts` compiles the result to prove it.
 *
 * Node-only: `json-schema-to-typescript` pulls in Node built-ins.
 */

import { normalizeSchema, normalizeTypes } from '@toolgraph/schema-core';
import { compile } from 'json-schema-to-typescript';

import type {
  CodegenResult,
  GeneratedFile,
  JsonSchema,
  JsonSchemaType,
  McpToolDescriptor,
  ToolGraphDocument,
} from './contract';
import {
  arrayBranchLength,
  buildValueTree,
  isArrayBranch,
  isValidTsIdentifier,
  pointerToAccessPath,
  quoteTs,
  toCamelCase,
  toPascalCase,
  toSnakeCase,
  uniqueName,
  type ValueTree,
} from './graph';
import { planGraph, type Assignment, type GraphPlan } from './plan';

/** `compile()` types its argument through `json-schema`, which we do not depend on. */
type CompilerSchema = Parameters<typeof compile>[0];

const BANNER = '/* Generated by toolgraph. Do not edit by hand. */';
const SDK_PACKAGE = '@modelcontextprotocol/sdk';
const CLIENT_IMPORT = `import type { Client } from '${SDK_PACKAGE}/client/index.js';`;

/** Deep enough for any hand-written tool schema; short enough to stay bounded. */
const MAX_SCHEMA_DEPTH = 12;

/* -------------------------------------------------------------------------- */
/* Names                                                                       */
/* -------------------------------------------------------------------------- */

interface ToolNames {
  inputType: string;
  outputType: string;
  schemaConst: string;
  fn: string;
}

/**
 * One name per tool per role, allocated once so `types.ts`, `schemas.ts`,
 * `client.ts` and `run.ts` cannot drift apart. Two servers exporting the same
 * tool name is normal, hence the dedupe.
 */
function allocateNames(tools: McpToolDescriptor[]): Map<McpToolDescriptor, ToolNames> {
  const types = new Set<string>(['GraphInput', 'GraphOutput']);
  const values = new Set<string>(['runGraph', 'client', 'input']);
  const names = new Map<McpToolDescriptor, ToolNames>();

  for (const tool of tools) {
    const pascal = toPascalCase(tool.name);
    const camel = toCamelCase(tool.name);
    names.set(tool, {
      inputType: uniqueName(`${pascal}Input`, types),
      outputType: uniqueName(`${pascal}Output`, types),
      fn: uniqueName(camel, values),
      schemaConst: uniqueName(`${camel}InputSchema`, values),
    });
  }
  return names;
}

function namesFor(names: Map<McpToolDescriptor, ToolNames>, tool: McpToolDescriptor): ToolNames {
  const found = names.get(tool);
  if (!found) throw new Error(`No generated name was allocated for the tool "${tool.name}".`);
  return found;
}

/** First occurrence wins, so the plan and the generator agree on object identity. */
function dedupeTools(tools: McpToolDescriptor[]): McpToolDescriptor[] {
  const seen = new Set<string>();
  const out: McpToolDescriptor[] = [];
  for (const tool of tools) {
    const key = `${tool.serverId} ${tool.name}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(tool);
  }
  return out;
}

/* -------------------------------------------------------------------------- */
/* Schema preparation                                                          */
/* -------------------------------------------------------------------------- */

const SCHEMA_MAPS = ['properties', 'patternProperties', '$defs', 'definitions'] as const;
const SCHEMA_LISTS = ['anyOf', 'oneOf', 'allOf', 'prefixItems'] as const;
const SCHEMA_SLOTS = ['items', 'not', 'if', 'then', 'else', 'additionalProperties'] as const;

/** Visit every position that holds a schema, and no position that merely looks like one. */
function visitSchemas(schema: JsonSchema, visit: (node: JsonSchema) => void): void {
  const seen = new Set<JsonSchema>();
  const walk = (node: JsonSchema): void => {
    if (seen.has(node)) return;
    seen.add(node);
    visit(node);
    for (const key of SCHEMA_MAPS) {
      const map = node[key];
      if (!map || typeof map !== 'object') continue;
      for (const child of Object.values(map as Record<string, unknown>)) {
        if (isSchemaObject(child)) walk(child);
      }
    }
    for (const key of SCHEMA_LISTS) {
      const list = node[key];
      if (!Array.isArray(list)) continue;
      for (const child of list) if (isSchemaObject(child)) walk(child);
    }
    for (const key of SCHEMA_SLOTS) {
      const child = node[key];
      if (isSchemaObject(child)) walk(child);
    }
  };
  walk(schema);
}

function isSchemaObject(value: unknown): value is JsonSchema {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * Strip `title` and `$id` from every schema in the document.
 *
 * json-schema-to-typescript names a declaration after its `title` when it has
 * one, in preference to the name we pass. Two tools that both call a field
 * "Result" would then emit two `export interface Result` declarations into one
 * file. Dropping the annotation makes the naming ours, and so predictable.
 */
function stripDeclarationNames(schema: JsonSchema): void {
  visitSchemas(schema, (node) => {
    delete node.title;
    delete node.$id;
    delete node.$schema;
  });
}

interface NamespacedSchema {
  schema: JsonSchema;
  defs: Record<string, JsonSchema>;
}

/**
 * Lift a schema's own `$defs` into a prefixed, shareable namespace.
 *
 * Definitions become top-level interfaces, so `Item` from one tool and `Item`
 * from another would collide in `types.ts`. Renaming them up front — and
 * rewriting the `$ref`s that point at them — keeps every declaration unique
 * without any string surgery on the generated output.
 */
function namespaceDefs(source: JsonSchema, prefix: string): NamespacedSchema {
  const schema = structuredClone(source);
  const defs: Record<string, JsonSchema> = {};
  const mapping = new Map<string, string>();

  for (const container of ['$defs', 'definitions'] as const) {
    const original = schema[container];
    if (!original || typeof original !== 'object') continue;
    for (const [key, value] of Object.entries(original)) {
      const renamed = `${prefix}${toPascalCase(key)}`;
      mapping.set(`#/${container}/${key}`, `#/$defs/${renamed}`);
      defs[renamed] = value;
    }
    delete schema[container];
  }

  if (mapping.size > 0) rewriteRefs(schema, mapping);
  for (const def of Object.values(defs)) rewriteRefs(def, mapping);

  return { schema, defs };
}

/** Rewrite `$ref` strings, including refs that address a path inside a definition. */
function rewriteRefs(node: unknown, mapping: ReadonlyMap<string, string>): void {
  if (Array.isArray(node)) {
    for (const item of node) rewriteRefs(item, mapping);
    return;
  }
  if (typeof node !== 'object' || node === null) return;
  const record = node as Record<string, unknown>;
  const ref = record.$ref;
  if (typeof ref === 'string') {
    for (const [from, to] of mapping) {
      if (ref === from) {
        record.$ref = to;
        break;
      }
      if (ref.startsWith(`${from}/`)) {
        record.$ref = `${to}${ref.slice(from.length)}`;
        break;
      }
    }
  }
  for (const value of Object.values(record)) rewriteRefs(value, mapping);
}

/** Assemble one self-contained document jstt can compile on its own. */
function documentFor(schema: JsonSchema, typeName: string): JsonSchema {
  const { schema: body, defs } = namespaceDefs(schema, typeName);
  stripDeclarationNames(body);
  for (const def of Object.values(defs)) stripDeclarationNames(def);
  return Object.keys(defs).length > 0 ? { ...body, $defs: defs } : body;
}

async function compileType(
  schema: JsonSchema,
  typeName: string,
  subject: string,
  warnings: string[],
): Promise<string> {
  try {
    const output = await compile(
      documentFor(schema, typeName) as unknown as CompilerSchema,
      typeName,
      {
        bannerComment: '',
        additionalProperties: false,
      },
    );
    return output.trim();
  } catch (error) {
    warnings.push(
      `${subject} could not be turned into a TypeScript type (${describeError(error)}); it is typed as unknown.`,
    );
    return `export type ${typeName} = unknown;`;
  }
}

function describeError(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

/* -------------------------------------------------------------------------- */
/* Zod                                                                         */
/* -------------------------------------------------------------------------- */

interface ZodContext {
  root: JsonSchema;
  subject: string;
  warnings: string[];
}

function warnAt(ctx: ZodContext, pointer: string, problem: string): void {
  const where = pointer === '' ? 'its input' : `input field "${pointer}"`;
  ctx.warnings.push(`${ctx.subject}: ${where} ${problem}; the zod schema uses z.unknown() there.`);
}

/** A zod expression for `raw`. The first line is unindented; the rest sits under `indent`. */
function zodFor(
  raw: JsonSchema | undefined,
  pointer: string,
  ctx: ZodContext,
  indent: string,
  depth: number,
): string {
  if (depth > MAX_SCHEMA_DEPTH) {
    warnAt(ctx, pointer, 'nests deeper than the generator follows');
    return 'z.unknown()';
  }
  const schema = normalizeSchema(raw, ctx.root);
  if (!schema) {
    warnAt(ctx, pointer, 'could not be resolved');
    return 'z.unknown()';
  }

  if (schema.const !== undefined) {
    const literal = zodLiteral(schema.const);
    if (literal !== undefined) return literal;
    warnAt(ctx, pointer, 'is a const with a non-primitive value');
    return 'z.unknown()';
  }

  if (Array.isArray(schema.enum) && schema.enum.length > 0) {
    return zodEnum(schema.enum, pointer, ctx, indent);
  }

  const anyOf = Array.isArray(schema.anyOf) && schema.anyOf.length > 0 ? schema.anyOf : undefined;
  const oneOf = Array.isArray(schema.oneOf) && schema.oneOf.length > 0 ? schema.oneOf : undefined;
  const branches = anyOf ?? oneOf;
  if (branches) {
    if (!anyOf) {
      ctx.warnings.push(
        `${ctx.subject}: ${pointer === '' ? 'its input' : `input field "${pointer}"`} uses oneOf; the generated union accepts a value matching more than one branch.`,
      );
    }
    const members = branches.map((branch, index) =>
      zodFor(branch, `${pointer}/${index}`, ctx, `${indent}  `, depth + 1),
    );
    return renderUnion(members, indent);
  }

  const types = normalizeTypes(schema.type);
  if (types.length === 0) {
    const inferred = inferType(schema);
    if (inferred === undefined) {
      warnAt(ctx, pointer, 'declares no type');
      return 'z.unknown()';
    }
    return zodForType(inferred, schema, pointer, ctx, indent, depth);
  }
  if (types.length === 1 && types[0] !== undefined) {
    return zodForType(types[0], schema, pointer, ctx, indent, depth);
  }
  const members = types.map((type) =>
    zodForType(type, schema, pointer, ctx, `${indent}  `, depth + 1),
  );
  return renderUnion(members, indent);
}

/** A schema with no `type` still tells us what it is, if it has any structure. */
function inferType(schema: JsonSchema): JsonSchemaType | undefined {
  if (schema.properties || schema.required || schema.additionalProperties !== undefined) {
    return 'object';
  }
  if (schema.items || schema.prefixItems) return 'array';
  return undefined;
}

function zodForType(
  type: JsonSchemaType,
  schema: JsonSchema,
  pointer: string,
  ctx: ZodContext,
  indent: string,
  depth: number,
): string {
  switch (type) {
    case 'string':
      return 'z.string()';
    case 'number':
      return 'z.number()';
    case 'integer':
      return 'z.number().int()';
    case 'boolean':
      return 'z.boolean()';
    case 'null':
      return 'z.null()';
    case 'array':
      return zodArray(schema, pointer, ctx, indent, depth);
    case 'object':
      return zodObject(schema, pointer, ctx, indent, depth);
  }
}

function zodArray(
  schema: JsonSchema,
  pointer: string,
  ctx: ZodContext,
  indent: string,
  depth: number,
): string {
  if (Array.isArray(schema.prefixItems) && schema.prefixItems.length > 0) {
    const members = schema.prefixItems.map((item, index) =>
      zodFor(item, `${pointer}/${index}`, ctx, `${indent}  `, depth + 1),
    );
    return `z.tuple([\n${members.map((member) => `${indent}  ${member},`).join('\n')}\n${indent}])`;
  }
  if (!schema.items) {
    warnAt(ctx, `${pointer}/items`, 'has no item schema');
    return 'z.array(z.unknown())';
  }
  return `z.array(${zodFor(schema.items, `${pointer}/items`, ctx, indent, depth + 1)})`;
}

function zodObject(
  schema: JsonSchema,
  pointer: string,
  ctx: ZodContext,
  indent: string,
  depth: number,
): string {
  const properties = schema.properties ?? {};
  const keys = Object.keys(properties);
  const additional = schema.additionalProperties;

  if (keys.length === 0) {
    if (additional === false) return 'z.strictObject({})';
    if (isSchemaObject(additional)) {
      return `z.record(z.string(), ${zodFor(additional, `${pointer}/additionalProperties`, ctx, indent, depth + 1)})`;
    }
    return 'z.record(z.string(), z.unknown())';
  }

  const required = new Set(schema.required ?? []);
  const entries = keys.map((key) => {
    const value = zodFor(properties[key], `${pointer}/${key}`, ctx, `${indent}  `, depth + 1);
    const suffix = required.has(key) ? '' : '.optional()';
    const token = isValidTsIdentifier(key) ? key : quoteTs(key);
    return `${indent}  ${token}: ${value}${suffix},`;
  });

  const factory =
    additional === false
      ? 'z.strictObject'
      : additional === undefined
        ? 'z.object'
        : 'z.looseObject';
  if (isSchemaObject(additional)) {
    ctx.warnings.push(
      `${ctx.subject}: the object at "${pointer === '' ? '/' : pointer}" constrains its additional properties; the generated schema only allows them through.`,
    );
  }
  return `${factory}({\n${entries.join('\n')}\n${indent}})`;
}

function zodEnum(values: unknown[], pointer: string, ctx: ZodContext, indent: string): string {
  if (values.every((value) => typeof value === 'string')) {
    return `z.enum([${values.map((value) => quoteTs(value)).join(', ')}])`;
  }
  const members: string[] = [];
  for (const value of values) {
    const literal = zodLiteral(value);
    if (literal === undefined) {
      warnAt(ctx, pointer, 'is an enum containing a non-primitive value');
      return 'z.unknown()';
    }
    members.push(literal);
  }
  if (members.length === 1 && members[0] !== undefined) return members[0];
  return renderUnion(members, indent);
}

function zodLiteral(value: unknown): string | undefined {
  if (typeof value === 'string') return `z.literal(${quoteTs(value)})`;
  if (typeof value === 'boolean') return `z.literal(${String(value)})`;
  if (typeof value === 'number' && Number.isFinite(value)) return `z.literal(${String(value)})`;
  if (value === null) return 'z.null()';
  return undefined;
}

function renderUnion(members: string[], indent: string): string {
  if (members.length === 1 && members[0] !== undefined) return members[0];
  return `z.union([\n${members.map((member) => `${indent}  ${member},`).join('\n')}\n${indent}])`;
}

/* -------------------------------------------------------------------------- */
/* Literals                                                                    */
/* -------------------------------------------------------------------------- */

/** A static input, rendered as TypeScript source. */
function tsLiteral(value: unknown, indent: string): string {
  if (value === null) return 'null';
  if (typeof value === 'string') return quoteTs(value);
  if (typeof value === 'boolean') return String(value);
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'undefined';
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const items = value.map((item) => `${indent}  ${tsLiteral(item, `${indent}  `)},`);
    return `[\n${items.join('\n')}\n${indent}]`;
  }
  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>);
    if (entries.length === 0) return '{}';
    const lines = entries.map(([key, item]) => {
      const token = isValidTsIdentifier(key) ? key : quoteTs(key);
      return `${indent}  ${token}: ${tsLiteral(item, `${indent}  `)},`;
    });
    return `{\n${lines.join('\n')}\n${indent}}`;
  }
  // `undefined`, and anything else JSON cannot carry, has no useful spelling.
  return 'undefined';
}

function renderTree(tree: ValueTree, indent: string, warnings: string[]): string {
  if (tree.kind === 'leaf') return tree.expr;
  const { children } = tree;
  if (children.size === 0) return '{}';

  if (isArrayBranch(children)) {
    const length = arrayBranchLength(children);
    const items: string[] = [];
    for (let index = 0; index < length; index += 1) {
      const child = children.get(String(index));
      if (child === undefined) {
        warnings.push(`Nothing feeds index ${index} of an array argument; it is left undefined.`);
        items.push(`${indent}  undefined as never,`);
        continue;
      }
      items.push(`${indent}  ${renderTree(child, `${indent}  `, warnings)},`);
    }
    return `[\n${items.join('\n')}\n${indent}]`;
  }

  const lines = [...children.entries()].map(([key, child]) => {
    const token = isValidTsIdentifier(key) ? key : quoteTs(key);
    return `${indent}  ${token}: ${renderTree(child, `${indent}  `, warnings)},`;
  });
  return `{\n${lines.join('\n')}\n${indent}}`;
}

/* -------------------------------------------------------------------------- */
/* Files                                                                       */
/* -------------------------------------------------------------------------- */

async function typesFile(
  tools: McpToolDescriptor[],
  names: Map<McpToolDescriptor, ToolNames>,
  plan: GraphPlan,
  inputKeys: Map<string, string>,
  outputKeys: Map<string, string>,
  warnings: string[],
): Promise<GeneratedFile> {
  const blocks: string[] = [];

  for (const tool of tools) {
    const { inputType, outputType } = namesFor(names, tool);
    blocks.push(
      await compileType(tool.inputSchema, inputType, `The input of "${tool.name}"`, warnings),
    );
    if (tool.outputSchema) {
      blocks.push(
        await compileType(tool.outputSchema, outputType, `The output of "${tool.name}"`, warnings),
      );
    } else {
      blocks.push(
        `/** \`${tool.name}\` declares no output schema, so its result cannot be typed. */\nexport type ${outputType} = unknown;`,
      );
    }
  }

  blocks.push(
    await compileType(
      boundarySchema(
        plan.inputs.map((entry) => ({
          key: keyFor(inputKeys, entry.nodeId),
          schema: entry.schema,
        })),
      ),
      'GraphInput',
      'The graph input',
      warnings,
    ),
  );
  blocks.push(
    await compileType(
      boundarySchema(
        plan.outputs.map((entry) => ({
          key: keyFor(outputKeys, entry.nodeId),
          schema: entry.schema,
        })),
      ),
      'GraphOutput',
      'The graph output',
      warnings,
    ),
  );

  return {
    path: 'types.ts',
    contents: `${BANNER}\n\n${blocks.join('\n\n')}\n`,
  };
}

/** One object with a property per boundary node, so 0, 1 and many all read alike. */
function boundarySchema(entries: Array<{ key: string; schema: JsonSchema }>): JsonSchema {
  const properties: Record<string, JsonSchema> = {};
  for (const entry of entries) properties[entry.key] = entry.schema;
  return {
    type: 'object',
    additionalProperties: false,
    properties,
    required: entries.map((entry) => entry.key),
  };
}

function keyFor(keys: Map<string, string>, nodeId: string): string {
  const key = keys.get(nodeId);
  if (key === undefined) throw new Error(`No generated key was allocated for node "${nodeId}".`);
  return key;
}

function schemasFile(
  tools: McpToolDescriptor[],
  names: Map<McpToolDescriptor, ToolNames>,
  warnings: string[],
): GeneratedFile {
  const blocks = tools.map((tool) => {
    const { schemaConst } = namesFor(names, tool);
    const ctx: ZodContext = { root: tool.inputSchema, subject: tool.name, warnings };
    const expression = zodFor(tool.inputSchema, '', ctx, '', 0);
    return `/** Runtime validation for the \`${tool.name}\` tool input. */\nexport const ${schemaConst} = ${expression};`;
  });

  const body = blocks.length > 0 ? blocks.join('\n\n') : '// This graph references no tools.';
  return {
    path: 'schemas.ts',
    contents: `${BANNER}\n\nimport { z } from 'zod';\n\n${body}\n`,
  };
}

function clientFile(
  tools: McpToolDescriptor[],
  names: Map<McpToolDescriptor, ToolNames>,
): GeneratedFile {
  const typeImports: string[] = [];
  const schemaImports: string[] = [];
  const functions: string[] = [];

  for (const tool of tools) {
    const { inputType, outputType, schemaConst, fn } = namesFor(names, tool);
    typeImports.push(inputType, outputType);
    schemaImports.push(schemaConst);
    const doc = tool.description ? `\n * ${tool.description.replace(/\s+/g, ' ').trim()}` : '';
    functions.push(
      `/**\n * Call the \`${tool.name}\` tool.${doc}\n */\n` +
        `export async function ${fn}(client: Client, input: ${inputType}): Promise<${outputType}> {\n` +
        `  const args = ${schemaConst}.parse(input);\n` +
        `  return callTool<${outputType}>(client, ${quoteTs(tool.name)}, args);\n` +
        `}`,
    );
  }

  const imports = [CLIENT_IMPORT];
  if (schemaImports.length > 0) {
    imports.push(`import { ${schemaImports.join(', ')} } from './schemas.js';`);
    imports.push(`import type { ${typeImports.join(', ')} } from './types.js';`);
  }

  const helpers = `/**
 * Unwrap an MCP tool result.
 *
 * Servers may answer with \`structuredContent\`, or with a text block holding
 * JSON, or with plain prose. All three are accepted, in that order.
 */
async function callTool<T>(client: Client, name: string, args: unknown): Promise<T> {
  const result = await client.callTool({ name, arguments: args as Record<string, unknown> });
  if (result.isError === true) {
    throw new Error(\`The MCP tool \${name} reported an error: \${firstText(result.content) ?? 'no details'}\`);
  }
  if (result.structuredContent !== undefined) {
    return result.structuredContent as T;
  }
  const text = firstText(result.content);
  if (text === undefined) {
    return undefined as T;
  }
  try {
    return JSON.parse(text) as T;
  } catch {
    return text as T;
  }
}

function firstText(content: unknown): string | undefined {
  if (!Array.isArray(content)) return undefined;
  for (const block of content as Array<{ type?: unknown; text?: unknown }>) {
    if (block.type === 'text' && typeof block.text === 'string') return block.text;
  }
  return undefined;
}`;

  const body = functions.length > 0 ? `${helpers}\n\n${functions.join('\n\n')}` : helpers;
  return {
    path: 'client.ts',
    contents: `${BANNER}\n\n${imports.join('\n')}\n\n${body}\n`,
  };
}

function runFile(
  plan: GraphPlan,
  names: Map<McpToolDescriptor, ToolNames>,
  inputKeys: Map<string, string>,
  outputKeys: Map<string, string>,
  warnings: string[],
): GeneratedFile {
  const usedFunctions: string[] = [];
  const usedTypes = new Set<string>(['GraphInput', 'GraphOutput']);
  const taken = new Set<string>(['client', 'input', 'runGraph']);
  for (const tool of plan.usedTools) {
    const { fn } = namesFor(names, tool);
    usedFunctions.push(fn);
    taken.add(fn);
  }

  const variables = new Map<string, string>();
  const statements: string[] = [];

  for (const step of plan.steps) {
    const { inputType, fn } = namesFor(names, step.tool);
    usedTypes.add(inputType);
    const base = toCamelCase(step.label);
    const argsName = uniqueName(`${base}Args`, taken);
    const resultName = uniqueName(`${base}Result`, taken);
    variables.set(step.nodeId, resultName);

    const { tree, warnings: treeWarnings } = buildValueTree(
      step.assignments.map((assignment) => ({
        pointer: assignment.pointer,
        expr: expressionFor(assignment, plan, variables, inputKeys, warnings),
      })),
    );
    for (const warning of treeWarnings) warnings.push(`${step.label}: ${warning}`);

    const value = tree === undefined ? '{}' : renderTree(tree, '  ', warnings);
    statements.push(`  const ${argsName}: ${inputType} = ${value};`);
    statements.push(`  const ${resultName} = await ${fn}(client, ${argsName});`);
    statements.push('');
  }

  const returnEntries = plan.outputs.map((output) => {
    const { tree, warnings: treeWarnings } = buildValueTree(
      output.assignments.map((assignment) => ({
        pointer: assignment.pointer,
        expr: expressionFor(assignment, plan, variables, inputKeys, warnings),
      })),
    );
    for (const warning of treeWarnings) warnings.push(`${output.label}: ${warning}`);
    const value = tree === undefined ? '{}' : renderTree(tree, '    ', warnings);
    return `    ${keyFor(outputKeys, output.nodeId)}: ${value},`;
  });

  const returnStatement =
    returnEntries.length > 0 ? `  return {\n${returnEntries.join('\n')}\n  };` : '  return {};';

  const imports = [CLIENT_IMPORT];
  if (usedFunctions.length > 0) {
    imports.push(`import { ${usedFunctions.join(', ')} } from './client.js';`);
  }
  imports.push(`import type { ${[...usedTypes].join(', ')} } from './types.js';`);

  const body = [...statements, returnStatement].join('\n');
  const contents =
    `${BANNER}\n\n${imports.join('\n')}\n\n` +
    `/**\n * Run the ${quoteTs(plan.name)} graph, one tool at a time, in dependency order.\n */\n` +
    `export async function runGraph(client: Client, input: GraphInput): Promise<GraphOutput> {\n` +
    `${body}\n}\n`;

  return { path: 'run.ts', contents };
}

function expressionFor(
  assignment: Assignment,
  plan: GraphPlan,
  variables: ReadonlyMap<string, string>,
  inputKeys: ReadonlyMap<string, string>,
  warnings: string[],
): string {
  if (assignment.kind === 'static') return tsLiteral(assignment.value, '  ');

  const inputKey = inputKeys.get(assignment.sourceNodeId);
  if (inputKey !== undefined) {
    return `input.${inputKey}${pointerToAccessPath(assignment.sourceHandle, 'ts')}`;
  }
  const variable = variables.get(assignment.sourceNodeId);
  if (variable === undefined) {
    // Only reachable if the plan is inconsistent with itself; say so rather
    // than emit a reference to a variable that does not exist.
    throw new Error(
      `Node "${assignment.sourceNodeId}" feeds another node but produces no value in "${plan.name}".`,
    );
  }
  void warnings;
  return `${variable}${pointerToAccessPath(assignment.sourceHandle, 'ts')}`;
}

function packageJsonFile(plan: GraphPlan): GeneratedFile {
  const manifest = {
    name: packageSlug(plan.name),
    version: '0.1.0',
    private: true,
    description: `Generated MCP client for the ${plan.name} graph.`,
    type: 'module',
    dependencies: {
      [SDK_PACKAGE]: '^1.20.0',
      zod: '^4.0.0',
    },
  };
  return { path: 'package.json', contents: `${JSON.stringify(manifest, null, 2)}\n` };
}

function packageSlug(name: string): string {
  const slug = toSnakeCase(name)
    .replace(/_/g, '-')
    .replace(/^-+|-+$/g, '');
  return slug.length > 0 ? slug : 'mcp-graph-export';
}

function readmeFile(plan: GraphPlan, names: Map<McpToolDescriptor, ToolNames>): GeneratedFile {
  const steps = plan.steps
    .map((step, index) => `${index + 1}. \`${step.tool.name}\` — ${step.label}`)
    .join('\n');

  const contents = `# ${plan.name}

Generated TypeScript client for the **${plan.name}** graph.

## What is in here

| File | What it holds |
| --- | --- |
| \`types.ts\` | An interface per tool input and output, plus \`GraphInput\` and \`GraphOutput\`. |
| \`schemas.ts\` | A zod schema per tool input, used to validate before every call. |
| \`client.ts\` | One typed \`async\` function per tool, wrapping \`client.callTool\`. |
| \`run.ts\` | \`runGraph\`, the whole graph as straight-line code. |

## Install

\`\`\`sh
npm install
\`\`\`

The only dependencies are \`zod\` and \`${SDK_PACKAGE}\`.

## Run

\`\`\`ts
import { Client } from '${SDK_PACKAGE}/client/index.js';
import { StdioClientTransport } from '${SDK_PACKAGE}/client/stdio.js';

import { runGraph } from './run.js';

const client = new Client({ name: '${packageSlug(plan.name)}', version: '0.1.0' });
await client.connect(new StdioClientTransport({ command: 'your-mcp-server', args: [] }));

const output = await runGraph(client, {
  /* fill in GraphInput */
});
console.log(output);
\`\`\`

Imports carry a \`.js\` extension, so the bundle type-checks and runs under
Node's ESM resolution as well as under a bundler or \`tsx\`.

## The order it runs in

${steps.length > 0 ? steps : 'This graph calls no tools.'}

## Tools it wraps

${
  plan.usedTools.length > 0
    ? plan.usedTools
        .map((tool) => `- \`${tool.name}\` → \`${namesFor(names, tool).fn}()\``)
        .join('\n')
    : '- none'
}

## It does not depend on toolgraph

This bundle was generated by toolgraph, but nothing in it imports toolgraph, and
no file here calls back to it. Delete the generator, take the repository
offline, or export once and never open the canvas again — this code keeps
working, because it only ever talks to zod and the MCP SDK.
`;

  return { path: 'README.md', contents };
}

/* -------------------------------------------------------------------------- */
/* Entry point                                                                 */
/* -------------------------------------------------------------------------- */

/**
 * Generate a standalone TypeScript bundle for `doc`.
 *
 * Async because json-schema-to-typescript is: it formats what it emits, and
 * doing that by hand would mean reimplementing an entire pretty-printer.
 */
export async function generateTypeScript(
  doc: ToolGraphDocument,
  tools: McpToolDescriptor[],
): Promise<CodegenResult> {
  const unique = dedupeTools(tools);
  const plan = planGraph(doc, unique);
  const warnings = [...plan.warnings];
  const names = allocateNames(unique);

  const takenKeys = new Set<string>();
  const inputKeys = new Map(
    plan.inputs.map((entry) => [entry.nodeId, uniqueName(toCamelCase(entry.label), takenKeys)]),
  );
  const outputKeys = new Map(
    plan.outputs.map((entry) => [entry.nodeId, uniqueName(toCamelCase(entry.label), takenKeys)]),
  );

  const files: GeneratedFile[] = [
    await typesFile(unique, names, plan, inputKeys, outputKeys, warnings),
    schemasFile(unique, names, warnings),
    clientFile(unique, names),
    runFile(plan, names, inputKeys, outputKeys, warnings),
    packageJsonFile(plan),
    readmeFile(plan, names),
  ];

  return { target: 'typescript', files, warnings };
}
